version: "3.9"
services:
  db:
    container_name: postgre-db
    image: postgres:alpine
    volumes:
      - ./database/db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      - POSTGRES_PASSWORD=forum
      - POSTGRES_USER=forum
      - POSTGRES_DB=forum
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 1s
      retries: 3
      start_period: 30s
      timeout: 10s
  backend:
    container_name: backend
    build: ./backend
    volumes:
      - ./database/db/init-db.sql:/go/db/init-db.sql
    # restart: always
    ports:
     - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_PASSWORD=forum
      - POSTGRES_USER=forum
      - POSTGRES_DB=forum
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - SERVER_PORT=8080
