global:
  scrape_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
  - job_name: backend-1
    static_configs:
      - targets:
          - load-balance-backend-1:8000
  - job_name: backend-2
    static_configs:
      - targets:
          - load-balance-backend-2:8000
