global:
  scrape_interval: 1s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
  - job_name: database
    static_configs:
      - targets:
          - 10.0.0.24:9187
  - job_name: backend-1
    static_configs:
      - targets:
          - 10.0.0.19:8000
          - 10.0.0.19:9100
  - job_name: backend-2
    static_configs:
      - targets:
          - 10.0.0.26:8000
          - 10.0.0.26:9100
  # - job_name: backend-3
  #   static_configs:
  #     - targets:
  #         - load-balance-backend-3:8000
  #         - load-balance-backend-3:9100
